############# English navigation ##############

# main menu
[[main]]
name = "L'association"
url = "/"
weight = 1

[[main]]
name = "La commune de Crevoux"
url = "commune-crevoux/"
weight = 2

[[main]]
name = "La pétition"
url = "la-petition/"
weight = 3

[[main]]
name = "Actualités"
url = "actualites/"
weight = 4

[[main]]
name = "Nous soutenir"
url = "nous-soutenir/"
weight = 5

#[[main]]
#name = "Elements"
#url = "elements/"
#weight = 5

#[[main]]
#name = "Pages"
#hasChildren = true
#weight = 6

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "blog/"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "contact/"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "authors/"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "categories/"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
