############# English navigation ##############

# Main menu configuration
# main menu
[[main]]
name = "L'association"
url = "l-association/"
weight = 1
# Submenu for L'association
[[main]]
parent = "L'association"
name = "Son Objet"
url = "l-association/#son-objet"
weight = 1

[[main]]
parent = "L'association"
name = "Le mot du Président"
url = "l-association/#le-mot-du-president"
weight = 2

[[main]]
parent = "L'association"
name = "L’équipe d’animation de l’UDSC"
url = "l-association/#lequipe-danimation-de-ludsc"
weight = 3

[[main]]
name = "La commune de Crevoux"
url = "commune-crevoux/"
weight = 2

[[main]]
name = "Nos actions"
url = "nos-actions/"
weight = 3
# Submenu for Nos actions
[[main]]
parent = "Nos actions"
name = "La pétition"
url = "nos-actions/#la-petition"
weight = 1

[[main]]
parent = "Nos actions"
name = "Réunions"
url = "nos-actions/#reunions"
weight = 2

[[main]]
name = "Actualités"
url = "actualites/"
weight = 4

[[main]]
parent = "Actualités"
name = "Agenda"
url = "actualites/agenda"
weight = 1

[[main]]
parent = "Actualités"
name = "La presse parle de nous"
url = "actualites/la-presse-parle-de-nous"
weight = 2

#[[main]]
#name = "Blog"
#url = "actualites/"
#weight = 4

[[main]]
name = "Nous soutenir"
url = "nous-soutenir/"
weight = 5

#[[main]]
#name = "Elements"
#url = "elements/"
#weight = 5

#[[main]]
#name = "Pages"
#hasChildren = true
#weight = 6

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "blog/"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "contact/"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "authors/"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "categories/"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
